chore(*): update-readme-16-jun-2023
IgniteUI/igniteui-blazor pull request #72
Opened 2023-06-16 13:11 UTC by radomirchev

closes #73 
Update of the Readme

2023-06-16 14:27 UTC, radomirchev commented
@ChronosSF @damyanpetev ready for review

2023-06-19 06:41 UTC, kdinev approved these changes

2023-06-26 10:45 UTC, kdinev requested changes

2023-06-26 10:45 UTC, kdinev commented on README.md
> +This repository is intended for clients to create feature requests, log bugs, and ask questions related to [Ignite UI for Blazor](https://www.infragistics.com/products/ignite-ui-blazor). Please note
```suggestion
This repository is intended for users to create feature requests, submit issues, and ask questions related to [Ignite UI for Blazor](https://www.infragistics.com/products/ignite-ui-blazor). Please note that this repository does not contain any source code or allow for direct code changes.
```

2023-06-26 10:45 UTC, kdinev commented on README.md
> +|Combo|:white_check_mark:|[Docs](https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/inputs/combo/overview)
Order them alphabetically.

2023-06-26 10:45 UTC, kdinev commented on README.md
> +|Pivot Grid|:white_check_mark:|[Docs](https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/pivot-grid/overview)|
Order them alphabetically.

2023-06-26 10:45 UTC, kdinev commented on README.md
> +Provide a complete windowing experience, splitting complex layouts into smaller, easier-to-manage panes.
```suggestion
Provide a complete multi-window experience, splitting complex layouts into smaller, easier-to-manage, and modify panes. 
```

2023-06-28 08:48 UTC, kdinev approved these changes

2023-06-28 08:48 UTC, merged